### ISSUE TITLE
Add "Musical Suit' and "FederAPI" to the mod list,

### ISSUE THREAD

**Issue by itayfeder** [jie65535/awesome-balatro#13]
Hello!
I have recently released 2 of my mods:
- Musical Suit: Adds a new suit (Notes ♪). with new jokers, tarot, and blind.
- FederAPI: An API library mod that allows to register vouchers, blinds, tarots, sounds, etc.

I would love if you could add them to the list.
Thanks!

**Comment by itayfeder** [comment]
Here's a link to the mods:
https://github.com/itayfeder/MusicalSuit
https://github.com/itayfeder/FederAPI-Balatro

**Comment by jie65535** [comment]
Thank you for your contribution. Next time, you can directly submit a pull request to make changes to the list.
