### ISSUE TITLE
Suggestion for a New Seal: Stapled

### ISSUE THREAD

**Issue by druss-hb** [jie65535/awesome-balatro#21]
I'm not sure where one would go to suggest a mod so I guess I'll do it here. What about a mod where one of the seals you can add is a staple to attach one card to another, and both cards will trigger in either the held cards or played deck while scoring, but one card will have to be selected to play in the hand. Stapled cards will still be drawn as one card, so this is effectively a short increase to your hand size.

I'll explain. Let's say you have a glass 2 of hearts and a bonus Jack of spades. You've conveniently got all the cards for a royal flush, and you add the Stapled Jack to your hand. So as well as triggering the bonus cards in the played hand, the x2 mult on scoring also procs, as well as the 1 in 4 chance to break. If the card gets destroyed in this instance, the card is no longer stapled. Another example: you staple 2 steel cards together in your hand to make a x3 mult on scoring while they stay in your hand.

To staple two cards together, the player will normally need to find "fusion" in the Spectral packs. There are other ways to staple cards but this would be the most common. And since this is going to be so powerful I'd say the best way to balance this would be to make it a seal, so you can't staple retriggers, gold on scoring hand etc.

As for jokers that take advantage of this mechanic I've theorycrafted a few:
Milton (uncommon): 1 in 6 chance that two random cards in played hand will get stapled.
Attachment issues (uncommon): Add double the rank value of the unplayed side of a stapled card to mult
Dossier (rare): +16 mult for every stapled card in currently held deck

Let me know what you think and if this is doable

**Comment by jie65535** [comment]
A good idea, but I suggest you post your request on the official [Discord](https://discord.gg/balatro) Modding channel so that the most developers can see it.
