### ISSUE TITLE
Balatro计时mod[Speedrun Timer]基于Steamodded?

### ISSUE THREAD

**Issue by SkyStreet** [jie65535/awesome-balatro#33]
Discord指向的github链接[Ankh](https://github.com/MathIsFun0/Ankh/tree/main)说通过Thunderstor或者Lovely来安装诶，请问可以基于Steamodded吗

**Comment by jie65535** [comment]
看了一下，应该不可以，因为SpeedRun原则上禁止安装任何Mod，所以不支持ModLoader
