### ISSUE TITLE
Partial Mod/Art Theft

### ISSUE THREAD

**Issue by MikaSchoenmakers** [jie65535/awesome-balatro#35]
The mod [MojiJoker](https://github.com/mojimoon/mojijoker/tree/main) has stolen assets from me and other mod creators, including MoreFluff, JankJonklers and Betmma's Jokers to name some. It has also stolen some actual ideas and implemented them as their own Jokers. I think it would be best to not allow this mod on the list until some changes are made to combat these issues.

**Comment by jie65535** [comment]
I have communicated with the author and he has decided to temporarily close the repo. Thank you for your report!
